### ISSUE TITLE
Landing Page 'Hover Cursor' - indicator when an image or text is clickable

### ISSUE THREAD

**Issue by PaulaPaul** [greyshore/MusicTree.Me#16]
Sasha requested a visual indication ('hover cursor') for the home page so that when you hover over the instrument image or the family name (Woodwinds, Keyboards... etc), you have a visual cursor indication that they are 'clickable'

@duggiemitchell  can you take this one? Marjani also suggested some padding around the landing page images for alignment/space-
I can pick up work on the onboarding flow (allowing the creation of a login if that's ok)

**Comment by duggiemitchell** [comment]
I'm on it. I made some edits recently to padding on the instruments but will double check its enough as I work on this.

**Comment by duggiemitchell** [comment]
@PaulaPaul something like this? 
https://www.loom.com/share/4bc6be14e6dd49a9bfb88fe572a36c74

**Comment by duggiemitchell** [comment]
Closing, merged into prod
